### ISSUE TITLE
Lỗi khi build project

### ISSUE THREAD

**Issue by locnv2805** [SE04-9-1/SE04-Nhom9.1#7]

**Comment by locnv2805** [comment]
hiện tại mình gặp một số lỗi khi build, mong mọi người cùng thảo luận, giải đáp cũng như hỗ trợ thêm với ạ.
Một số lỗi: 
+) ReleaseAllScriptCaches did not release all script caches!
+) NullReferenceException: Object reference not set to an instance of an object UnityEditor.UIElements.UIElementsEditorUtility..cctor () (at <68af50843d0a45398c92799647332ec2>:0)
Rethrow as TypeInitializationException: The type initializer for 'UnityEditor.UIElements.UIElementsEditorUtility' threw an exception.
UnityEditor.EditorWindow.CreateRoot () (at <68af50843d0a45398c92799647332ec2>:0)
UnityEditor.EditorWindow.get_rootVisualElement () (at <68af50843d0a45398c92799647332ec2>:0)
UnityEditor.HostView.UpdateViewMargins (UnityEditor.EditorWindow view) (at <68af50843d0a45398c92799647332ec2>:0)
UnityEditor.HostView.SetWindow (UnityEditor.ContainerWindow win) (at <68af50843d0a45398c92799647332ec2>:0)
UnityEditor.View.Initialize (UnityEditor.ContainerWindow win) (at <68af50843d0a45398c92799647332ec2>:0)
UnityEditor.ContainerWindow.OnEnable () (at <68af50843d0a45398c92799647332ec2>:0)

**Comment by Klyvngo** [comment]
Vylk said:
> Bạn có thể thử gỡ bỏ Unity UI trong Package Manager và cài đặt lại

**Comment by Klyvngo** [comment]
Hoặc Deleting all folders Assets/Packages/Project Settings/gitignore
